### PR TITLE
Basic Schema + Validation

### LINKED ISSUE #2: Schema for combinations
__Is your feature request related to a problem? Please describe__

Based on the work of #1 we should extend the schema with logical combinations.

The [PropertiesPanel Template validator](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L181) is doing exactly this. It marks a property as invalid, if a certain combination is not given, e.g. when `type` equals `Dropdown`, but no `choices` are given.

__Describe the solution you'd like__

The JSON schema should handle this as well and validate it for those combinations

* [x] Identify all combinations, cf. [PropertiesPanel Template validator](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L181)
* [x] Add definitions / combinations / conditionals to JSON schema
  * [x] [property types](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L190)
  * [x] [dropdown has choices](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L197)
  * [x] [dropdown choices have value and name](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L204)
  * [x] [no binding](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L212)
  * [x] [binding types](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L216)
  * [x] [property, camunda:property, camunda:inputParameter, camunda:field require name](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L223)
  * [x] [camunda:outputParameter requires source](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L235)
  * [x] [camunda:in requires variables or target](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L243)
  * [x] [camunda:out requires variables, source or sourceExpression](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L253)
  * [x] [camunda:executionListener requires Hidden type](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js#L263)

__Describe alternatives you've considered__

Let it freestyle as it is.

__Additional context__

The JSON Schema definition handles such functionality via definitions: https://json-schema.org/understanding-json-schema/reference/combining.html#allof

Since we use meta-schema version draft7, we can also use [conditionals](https://json-schema.org/understanding-json-schema/reference/conditionals.html)

Related to https://github.com/camunda/camunda-modeler/issues/1939

### PR DESCRIPTION
**Pull request by pinussilvestrus**
__Which issue does this PR address?__

Closes #2 

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/.github/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
### Slackday Summary 

* Created [JSON schema file](https://github.com/bpmn-io/element-templates-json-schema/blob/3781e55dc004d9da7e8f1712b278828aea950dff/resources/element-templates.schema.json) for (single) element template object
* Created validation tool (based on [`ajv`](https://github.com/ajv-validator/ajv)) to validate element templates
* Can be used as a foundation for Element Templates tooling (validation, automatic JSON Forms)
* Releasing the JSON schema needs a stable element template foundation
* Proposal: do a lightning talk about JSON schemas

### Further Tasks
* Better schema information for scopes
* Double check [required properties](https://github.com/bpmn-io/element-templates-json-schema/blob/3781e55dc004d9da7e8f1712b278828aea950dff/resources/element-templates.schema.json#L7)
* Validation: line numbers / location / pointer for errors
* Validation: validate combinations (e.g. type='Dropdown' & choices), cf. Validator in Properties Panel, https://json-schema.org/understanding-json-schema/reference/combining.html#allof
* More test cases for validation of schema
* CLI tool

**Comment by pinussilvestrus** [comment]
This basic version is ready to review now. I also asked the Cawemo team so they could give feedback once they tackle JSON validation.

**Comment by pinussilvestrus** [comment]
I start working on https://github.com/bpmn-io/element-templates-json-schema/issues/2 inside this PR. I think it makes sense to include those changes when merging the first iteration.

**Review by nikku — COMMENTED** [review]
Looks good to me:

* :heavy_check_mark: tests
* :heavy_check_mark: schema

**Pull request merged**
